/-
  Environment-based dependency extraction for VeriSoftBench.

  Usage: lake env lean --run extract_deps.lean

  Input (stdin): JSON array of {"module": "Foo.Bar", "name": "Foo.Bar.baz"}
  Output (stdout): JSON array of per-theorem dependency records.

  Relies on `lake env` having set LEAN_PATH correctly.
  Compatible with Lean 4.8–4.26:
    - Uses `getModuleIdxFor?` + `allImportedModuleNames` instead of `getModuleFor?`
    - Uses custom `strContains` instead of `String.containsSubstr`
    - Uses `Std.HashMap` → avoided entirely (not stable across versions)
    - Uses positional args for `importModules`
-/
import Lean
open Lean

-- ============================================================
-- String utilities
-- ============================================================

/-- Check if `needle` is a substring of `haystack`. -/
def strContains (haystack needle : String) : Bool :=
  let hLen := haystack.length
  let nLen := needle.length
  if nLen == 0 then true
  else if nLen > hLen then false
  else Id.run do
    for i in List.range (hLen - nLen + 1) do
      if haystack.extract ⟨i⟩ ⟨i + nLen⟩ == needle then return true
    return false

/-- Find `needle` in `haystack` starting at character position `start`. -/
def findSubstrFrom (haystack needle : String) (start : Nat) : Option Nat := Id.run do
  let hLen := haystack.length
  let nLen := needle.length
  if nLen == 0 then return some start
  let mut i := start
  while i + nLen <= hLen do
    if haystack.extract ⟨i⟩ ⟨i + nLen⟩ == needle then return some i
    i := i + 1
  return none

-- ============================================================
-- Environment helpers
-- ============================================================

/-- Get the module name for a constant.
    Uses `getModuleIdxFor?` + `allImportedModuleNames` for version compat. -/
def getModuleName (env : Environment) (constName : Name) : Option Name :=
  match env.getModuleIdxFor? constName with
  | none => none
  | some idx =>
    let names := env.allImportedModuleNames
    if h : idx.toNat < names.size then some names[idx.toNat] else none

-- ============================================================
-- Classification
-- ============================================================

/-- Library module prefixes — constants from these are "library", not "repo". -/
def libraryPrefixes : List String :=
  ["Init", "Std", "Lean", "Mathlib", "Aesop", "Qq", "ProofWidgets",
   "Batteries", "ImportGraph", "LeanSearchClient", "Plausible", "Cli", "Lake"]

def isLibraryModule (modName : Name) : Bool :=
  let s := modName.toString
  libraryPrefixes.any fun pfx => s == pfx || s.startsWith (pfx ++ ".")

/-- Filter auto-generated constants (recursors, equation lemmas, etc.). -/
def isAutoGenerated (n : Name) : Bool :=
  let s := n.toString
  strContains s ".rec" || strContains s ".casesOn" || strContains s ".recOn" ||
  strContains s ".noConfusion" || strContains s ".brecOn" || strContains s ".below" ||
  strContains s ".match_" || strContains s "._private." || strContains s "._cstage" ||
  strContains s ".injEq" || strContains s ".sizeOf_spec" || strContains s "._eq_" ||
  strContains s "._sizeOf_" || strContains s "._pack"

/-- Classify a `ConstantInfo` into a kind string for JSON output. -/
def classifyConstant (ci : ConstantInfo) : String :=
  match ci with
  | .thmInfo _ => "theorem" | .defnInfo _ => "def" | .axiomInfo _ => "axiom"
  | .opaqueInfo _ => "opaque" | .inductInfo _ => "inductive"
  | .ctorInfo _ => "constructor" | .recInfo _ => "recursor" | .quotInfo _ => "quot"

-- ============================================================
-- Transitive dependency collection
-- ============================================================

/-- Collect all constants used transitively, stopping at library module boundaries. -/
partial def collectTransitiveDeps (env : Environment) (initial : Array Name) : Array Name := Id.run do
  let mut visited : NameSet := {}
  let mut queue := initial.toList
  let mut result : Array Name := #[]
  while !queue.isEmpty do
    match queue with
    | [] => break
    | n :: rest =>
      queue := rest
      if visited.contains n then continue
      visited := visited.insert n
      if isAutoGenerated n then continue
      match env.find? n with
      | none => continue
      | some ci =>
        result := result.push n
        match getModuleName env n with
        | none => continue
        | some modName =>
          if isLibraryModule modName then continue
          for c in ci.type.getUsedConstants do
            if !visited.contains c then queue := c :: queue
          match ci.value? with
          | some v => for c in v.getUsedConstants do
              if !visited.contains c then queue := c :: queue
          | none => pure ()
  return result

-- ============================================================
-- JSON output helpers
-- ============================================================

def jsonEscape (s : String) : String :=
  s.foldl (fun acc c => match c with
    | '\"' => acc ++ "\\\"" | '\\' => acc ++ "\\\\"
    | '\n' => acc ++ "\\n" | '\t' => acc ++ "\\t"
    | c => acc.push c) ""

def jsonStr (s : String) : String := s!"\"{jsonEscape s}\""
def jsonBool (b : Bool) : String := if b then "true" else "false"
def jsonArr (items : List String) : String :=
  "[" ++ (items.intersperse ", " |> String.join) ++ "]"
def jsonObj (fields : List (String × String)) : String :=
  let inner := fields.map (fun (k, v) => s!"\"{jsonEscape k}\": {v}")
    |>.intersperse ", " |> String.join
  "{" ++ inner ++ "}"

-- ============================================================
-- Per-theorem extraction
-- ============================================================

/-- Extract dependency information for a single theorem from a loaded environment.
    Uses IO monad instead of Id.run to avoid interpreter issues across Lean versions.
    Outputs a dep_graph where each constant has type_deps and value_deps for the
    Python-side 3-rule algorithm to walk. -/
def extractOne (env : Environment) (moduleName thmName : Name) : IO String := do
  match env.find? thmName with
  | none => return jsonObj [("name", jsonStr thmName.toString), ("module", jsonStr moduleName.toString),
      ("error", jsonStr "constant not found in environment")]
  | some ci =>
    let stmtDeps := ci.type.getUsedConstants
    let proofDeps := match ci.value? with | some v => v.getUsedConstants | none => #[]
    let allDirect := (stmtDeps ++ proofDeps).toList.eraseDups.toArray
    let allTransitive := collectTransitiveDeps env allDirect
    let mut depEntries : Array String := #[]
    for dep in allTransitive do
      if dep == thmName then continue
      match env.find? dep with
      | none => continue
      | some depCi =>
        let depMod := getModuleName env dep |>.map Name.toString |>.getD "unknown"
        let kind := classifyConstant depCi
        let isRepo := match getModuleName env dep with
          | some m => !(isLibraryModule m) | none => false
        -- Compute per-constant type_deps and value_deps (filtered for auto-generated)
        let depTypeDeps := depCi.type.getUsedConstants.toList.filter (!isAutoGenerated ·)
        let depValDeps := match depCi.value? with
          | some v => v.getUsedConstants.toList.filter (!isAutoGenerated ·)
          | none => []
        depEntries := depEntries.push s!"\"{jsonEscape dep.toString}\": {jsonObj [
          ("module", jsonStr depMod), ("kind", jsonStr kind), ("is_repo", jsonBool isRepo),
          ("type_deps", jsonArr (depTypeDeps.map (fun n => jsonStr n.toString))),
          ("value_deps", jsonArr (depValDeps.map (fun n => jsonStr n.toString)))]}"
    let depsObj := "{" ++ (depEntries.toList.intersperse ", " |> String.join) ++ "}"
    return jsonObj [("name", jsonStr thmName.toString), ("module", jsonStr moduleName.toString),
      ("stmt_deps", jsonArr (stmtDeps.toList.map (fun n => jsonStr n.toString))),
      ("proof_deps", jsonArr (proofDeps.toList.map (fun n => jsonStr n.toString))),
      ("dep_graph", depsObj)]

-- ============================================================
-- Input parsing
-- ============================================================

/-- Parse JSON input: extract module and name from array of {"module":..., "name":...} objects. -/
def parseInput (input : String) : List (Name × Name) := Id.run do
  let mut results : List (Name × Name) := []
  let mut pos := 0
  let len := input.length
  while pos < len do
    match findSubstrFrom input "\"module\"" pos with
    | none => break
    | some mpos =>
      match findSubstrFrom input "\"" (mpos + 10) with
      | none => break
      | some vstart =>
        match findSubstrFrom input "\"" (vstart + 1) with
        | none => break
        | some ve =>
          let moduleName := input.extract ⟨vstart + 1⟩ ⟨ve⟩
          match findSubstrFrom input "\"name\"" ve with
          | none => break
          | some npos =>
            match findSubstrFrom input "\"" (npos + 8) with
            | none => break
            | some ns =>
              match findSubstrFrom input "\"" (ns + 1) with
              | none => break
              | some nend =>
                let thmName := input.extract ⟨ns + 1⟩ ⟨nend⟩
                results := results ++ [(moduleName.toName, thmName.toName)]
                pos := nend + 1
  return results

/-- Group entries by module name. -/
def groupByModule (entries : List (Name × Name)) : List (Name × List Name) :=
  let mods := entries.map Prod.fst |>.eraseDups
  mods.map fun m => (m, entries.filterMap fun (m', n) => if m' == m then some n else none)

-- ============================================================
-- Main
-- ============================================================

unsafe def main (_args : List String) : IO Unit := do
  let stdin ← IO.getStdin
  let mut buf := ""
  let mut done := false
  while !done do
    let line ← stdin.getLine
    if line.isEmpty then done := true
    else buf := buf ++ line
  let entries := parseInput buf
  if entries.isEmpty then
    IO.eprintln "No entries parsed from stdin"
    return
  let moduleGroups := groupByModule entries
  let mut results : List String := []
  for (modName, thms) in moduleGroups do
    let env ← try
      importModules #[{ module := modName }] {} 0
    catch e =>
      let errMsg := toString e
      for thm in thms do
        results := results ++ [jsonObj [("name", jsonStr thm.toString),
          ("module", jsonStr modName.toString),
          ("error", jsonStr s!"import failed: {errMsg}")]]
      continue
    for thm in thms do
      let r ← extractOne env modName thm
      results := results ++ [r]
  IO.println (jsonArr results)
